language: go

go:
  - 1.5

env:
  matrix:
    - TMP_GOOS=windows TMP_GOARCH=amd64

global:
  - secure: iK8Zcm1f3/BbCvMgEISgZ0WvmHpk2V4EQHycZlae1hGB2Xr8R9MmIV+fu19+lBu1QOSBpXmUeVJvSwfe9sJHYTKJbcsHeGQM7AIAESvIOiIIZbEDp98WGXwEfxQ1733TgeEX10St4PK8kE3v7G+E5qYhUffjO4DLuE9BfmaQRei2BbcG382rnj9c8vYWF4O00fZEzcDvnwvD9IaeQnB4Jy4e0kkHsIJfvOkwdxbLf6amX9Q7fF7SqBnxHgmvitHef2RBMjBfjT8StUqrBoUVt93j2XXY8m6WWpggaAjilWzvb9Kw9W4XwLryqM+cMCOnbx14SxElrAmmxKjdRFPlSuAWbVaX7O5rK4aANMxXJ7paNUk9bqaWXKor+NsUQ5HC3zPHTRHsmV53J2Yd9bk7n2joAswNXvdN1+KzHY87jUbxZLSakSJ7aSW8ac8MMaUAEzmZizzmqSWBNXfpWFmqvtpjS7fP2zwWfz6f2YWIoVL0n/4+jIWJTR+Ai6fT6RDK3J+gj9A3U4KC2k328nV5mTxFB8SkqWpmJ5RUE6gtE5AZzIcba0mF3l7qKAjD3RjugnPqZ+16fmjjOM60dEeFjhkS43kHF9b7yO+Lk2l+66ruQg4pERj2TbuZqGf6kb95zcflE2vZQ5IjtsswwiDWCIoOI2Praf5UU22fcMl7lkw=

before_install:
  - export GOOS=${TMP_GOOS}
  - export GOARCH=${TMP_GOARCH}
  - cp .netrc ~
  - chmod 600 ~/.netrc
  - chmod 600 .netrc

script:
  - go get -t -v ./...

after_success:
  - zip -r -j palette-updater-${TRAVIS_TAG}.zip $GOPATH/bin/*

deploy:
  provider: releases
  api_key:
    secure: Ht0/u0+sbmFcFGjRhgR1PKfGdykS9Lxj3f6dwthtvaRS9xqQ4wpx1loqr4zf73SvW5ZQbBNmAE1oYL/PK5Ey/yzJP1/Nu4cALRwkVREH+ZyxYBk2MH91/sPUrNoN5Gr/Nea4K762SX9gRkfewyx+zbbWIWGAaItKOT8C6IW6Ic/ZcymoJv3wO+CQsuLuwt90mn7h/bT4bbCDAA/4AgQ98XbeHy4ndlU+q5FIE2EnTjNisW8bGGA6WMcpDfW6b5/mMzikGlmR90xaiteTeBXnofydEpPfyfdazE4teNJVBNC9CRfJr92CUTW96UHqjmxq+FopiO8IyDHjjs7cWXAs94n5xRAa3zwg/lQcTQVlQSKhFHe4MRfNiYf8uocgKzx3eK2ZwCjVkwbEkNnfoXEUueZbNB5s4KUEQp4fTSQAxdwLS/o7jO7G0y/IrQaSeWzPWIjDNHOh0yEx9tjk/eFip43P7bKuldZIZcjGqwFh05dw+MufVRHpPM2Ubd7Be+w5AewqCNCiyhnNdQJMWBqq3NXmBBIavZoQTGDoAd1gRZP6A1x5LqvyywfAX7SFrawpaQKYenj0neEoyAT4tKLZRgMn13Rn655XOxl/aBr2HpgD2DNSA7/CV4JaW5aVq64C7LcqIyf/7Kos8hhsm1buToRJZVrrbiKXTzfO9petGiE=
  file: palette-updater-${TRAVIS_TAG}.zip
  on:
    repo: palette-software/palette-updater
    tags: true

notifications:
  email:
    on_success: never
    on_failure: never
