language: go
sudo: required

go:
  - 1.5

env:
  matrix:
    - TMP_GOOS=windows TMP_GOARCH=amd64
  global:
    - secure: "QrutktXEqep+IhC+00JzsyENmLuSPv2/0IwnEzwAf33dW/gcfx04HVRGsLAbXz2SdyRrYPMBDtNWJ3qf0wNEeIh0csuAJRH4bokqL+xdtDfTS36AR2WiZB7zVFZ2vKdwQsst51qRqPIR4G70tBP9ExNhQUGhXo5BwQXMPbNempU2PwUhnNWlSZtloD5KJu4mEuKuaVdTU2iwUrKPOZsSCcmLDizYqVAaXAiLRcNCPQceCnit0Ms7oXFhgyo6Vs/7kjPfIxm4wMgzd2mSg4lQfqvTBUBxIhGQyn60udimvPw3RO9RDTnyXRK8Ug39heBJPSXedaKxKrnlNVyIgsods0do2EFhhyR6Kw2HyYusAvDsEnZn2BWsF1sdUOWJ/b9EH8wfi4tnuKSDbV57MkLncN6rPeqhMn3XnVZSjwuPcjJQgFyHjSUK7BTRaXZmskU0GNitia4OCv75blVTwpCwPRASIvjoaMYZVOExbLxAE/ICOw2glSvhjtR38ALnqrL0rGX14yWtxaBstpvm2tJ2PBMUcsQF0RPA1/3/eDilG51cghFhWJQ/r7Tdt2x7XvPeuxfX9mm1uLMsvOrVw5BBisFafbhZo5d5UDdGzp1Gc9QFakn55OByk3rqp3Y5Zlb8GRkT7T+u5uCdsbWCKK1K+inD/x5TNQvAniOPvkJy+Pk="
    - PRODUCT_VERSION=v1.0.$TRAVIS_BUILD_NUMBER
    - OWNER=palette-software
    - PACKAGE=palette-updater

before_install:
  - export GOOS=${TMP_GOOS}
  - export GOARCH=${TMP_GOARCH}
  - cp .netrc ~
  - chmod 600 ~/.netrc
  - chmod 600 .netrc

script:
  - go get -t -v ./...

before_deploy:
  # PCKG_DIR is required in release-to-github.sh
  - export PCKG_DIR=`pwd`
  - export PCKG_FILE=palette-updater-${PRODUCT_VERSION}.zip
  - zip -r -j $PCKG_FILE $GOPATH/bin/*

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: $TRAVIS_BUILD_DIR/release-to-github.sh
  on:
    branch: master
    tags: false

notifications:
  email:
    on_success: never
    on_failure: never
